pkg/features/main/objects/FeatureFlag__mdt/FeatureFlag__mdt.object-meta.xml
<CustomObject>
    <description>Global Feature Flags used by the Custom Metadata Feature Implementation</description>
    <label>Feature Flag</label>
    <pluralLabel>Feature Flags</pluralLabel>
</CustomObject>

pkg/features/main/objects/FeatureFlag__mdt/fields/Enabled__c.field-meta.xml
<CustomField>
    <fullName>Enabled__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If true the feature has been enabled</description>
    <inlineHelpText>If true the feature has been enabled</inlineHelpText>
    <label>Enabled</label>
    <type>Checkbox</type>
</CustomField>

pkg/features/main/classes/CustomMetadataEnabledFeature.cls
/**
 * @description Feature Implementation that uses a global
 * custom metadata flag.
 */
public class CustomMetadataEnabledFeature extends Feature {
    /**
     * @description checks if the feature has been enabled via
     * a custom metadata flag
     *
     * @param featureName
     * @return true if enabled
     */
    public override Boolean isEnabled(String featureName) {
        FeatureFlag__mdt feature = FeatureFlag__mdt.getInstance(featureName);

        if (feature == null) {
            return false;
        }

        return feature.Enabled__c;
    }
}