pkg/core/main/objects/FeatureSetting__mdt/FeatureSetting__mdt.object-meta.xml
<CustomObject>
    <description>Mapping of a feature to its given implementation to check if its enabled</description>
    <label>Feature Setting</label>
    <pluralLabel>Feature Settings</pluralLabel>
</CustomObject>

pkg/core/main/objects/FeatureSetting__mdt/fields/Implementation__c.field-meta.xml
<CustomField>
    <fullName>Implementation__c</fullName>
    <description>Class Name for the feature implementation</description>
    <inlineHelpText>Class Name for the feature implementation</inlineHelpText>
    <label>Implementation</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

pkg/core/main/classes/CustomMetadataFeatureSettingsProvider.cls
/**
 * @description Feature Settings Provider that returns Feature Settings
 * from the FeatureSetting__mdt Custom Metadata
 */
public class CustomMetadataFeatureSettingsProvider implements FeatureSettingsProvider {
    /**
     * @description Returns Feature Setting Object by Feature Name
     *  if not found should return null
     * @param featureName
     * @return Feature Setting Object null if not found
     */
    public FeatureSetting getFeatureSettingByName(String featureName) {
        FeatureSetting__mdt featureSettingMetadata = FeatureSetting__mdt.getInstance(
            featureName
        );

        if (featureSettingMetadata == null) {
            return null;
        }

        FeatureSetting feature = new FeatureSetting(
            featureName,
            featureSettingMetadata?.Implementation__c
        );

        List<String> requiredFields = feature.implementation.getRequiredFields();
        Map<String, Object> params = new Map<String, Object>();

        for (String field : requiredFields) {
            params.put(field, featureSettingMetadata.get(field));
        }

        feature.implementation.setRequiredParameters(params);
        return feature;
    }
}